<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'All Products',
                'title' => '',
                'slug' => 'all-products',
                'parent_id' => 0,
                'short_description' => '<h1>ALL DIAMOND ENGAGEMENT RINGS</h1>',
                'description' => 'Description of the category',
                'image_url' => NULL,
                'enable_filter' => 0,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 05:56:31',
                'updated_at' => '2022-04-19 05:56:31',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Diamond Jewellery',
                'title' => 'Designer Diamond Jewellery',
                'slug' => 'diamond-jewellery',
                'parent_id' => 0,
                'short_description' => '<p>Traditionally bought for special occasions, diamond jewellery is now 
prevalent in today’s society. It marks a sign of luxury and a touch of 
elegance, our huge selection of diamond jewellery will brighten up any 
collection.</p>',
                'description' => '<br>',
                'image_url' => 'Category/1650348971-1280x375engagement-rings-banner.png',
                'enable_filter' => 0,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => 'Diamond Jewellery | GIA Certified | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our exclusive range of stunning GIA certified diamond jewellery, including earrings, pendants, bracelets and necklaces, handcrafted by local experts',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:06:28',
                'updated_at' => '2022-05-11 11:47:23',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Bracelets',
                'title' => 'CERTIFIED DIAMOND BRACELETS',
                'slug' => 'bracelets',
                'parent_id' => 2,
                'short_description' => '<h2>STUNNING BRACELETS FROM MARLOWS DIAMONDS</h2><p></p>',
                'description' => NULL,
                'image_url' => 'Category/1650348971-1280x375engagement-rings-banner.png',
                'enable_filter' => 0,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => 'Best Value luxurious Diamond Bracelets | Certified Diamond Jewellery | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Buy our studding collection of certified diamond bracelets. Call us today to buy online or stop by one of our jewellery stores and chat to an expert',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:18:38',
                'updated_at' => '2022-05-11 11:36:02',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Earrings',
                'title' => 'Explore Beautiful Diamond Earrings for Women',
                'slug' => 'earrings',
                'parent_id' => 2,
                'short_description' => '<p>For a woman, it is next to impossible to not want <a href="https://marlows-diamonds.co.uk/product-category/diamond-jewellery" target="_blank">diamond jewellery</a>. Growing up, every girl dreams of owning her very own diamond jewels. If you are also planning to buy your first diamond then we have some amazing designs in diamond earrings for women. Our range of earrings is made with the highest quality diamonds that give out the brightest dazzle when worn. If you want to experience the true joy of buying diamond earrings for women, then Marlow’s is the place for you. We have a wide range of diamond earrings in various designs, from studs to danglers, we have it all. After all, purchasing your first piece of diamond jewellery is a big decision and the excitement surrounding the occasion is second to none.</p><h2><strong>Buy GIA Certified Diamond Earrings for Women Online</strong></h2><p><a href="https://www.marlows-diamonds.co.uk/">Marlow’s</a> is your go-to shopping destination if you have been looking for a reliable service provider to purchase your first pair of diamond earrings online. All our diamonds are ethically sourced, so you can be sure that the diamonds dangling on your ears are completely conflict-free. All our diamond jewellery comes with a grading certificate by the <b><a href="https://marlows-diamonds.co.uk/gia-certified-diamonds" target="_blank">GIA </a></b>to give you the reassurance of the diamond you just bought. When you shop with us, you get an assortment of shapes and settings to choose from, whether that’s classic, modern or anything in between. From single solitaire studs to multi-stone chandeliers and drop earrings with other precious gemstones, you name it, we have it.</p><p>So what are you waiting for? Scroll down to check out the most amazing collection of the highest quality diamond earrings for women.</p><p></p>',
                'description' => '<div class="text_container">
<h2 class="vc_custom_heading">Complete Your Look with Dainty Diamond Earrings</h2>
<p class="vc_custom_heading">Who doesn’t love the dazzle of diamonds? A 
dangling pair of diamond earrings can add a whole lot of bling and 
glamour to the plainest outfits. Not only are diamond earrings a 
must-have for formal outings but also a chic add-on for daily wear. 
While plain diamond studs are an excellent choice for daily office wear,
dainty drop earrings are the go-to style for those early luncheons and 
dinner dates. Pair these up with both formal wear and casual dresses, 
and your whole look will be lifted in an instant!</p>
<h2>Get Quality Diamonds at Affordable Prices</h2>
<p class="vc_custom_heading">At Marlow’s, we offer the latest designs in
diamond earrings at the most affordable prices so that looking chic 
doesn’t burn a huge hole in your pocket! Our diamond earrings are 
stylish, made with the highest quality diamonds, and graded by experts 
at the GIA. With us, you get the promise of the purest quality gemstones
in the newest trending designs. We have some amazing designs in <a href="https://marlows-diamonds.co.uk/product-category/diamond-jewellery/earrings" target="_blank">diamond earrings</a> made by highly skilled professionals in various cuts; round, 
princess, oval, cushion, and what not! What makes it even better is our 
prices that will make buying your very own first piece of jewellery in 
diamonds so much easier!</p>
</div><p></p>',
                'image_url' => 'Category/1650348971-1280x375engagement-rings-banner.png',
                'enable_filter' => 0,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => 'Diamond Earrings for Women | Marlow&#039;s Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Find a beautiful collection of diamond earrings for Women at Marlow’s Diamonds. Shop online with free delivery, or visit our Birmingham and London Stores.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:24:57',
                'updated_at' => '2023-02-06 18:14:56',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Necklaces',
                'title' => 'DIAMOND NECKLACES',
                'slug' => 'necklaces',
                'parent_id' => 2,
                'short_description' => 'CERTIFIED DIAMOND NECKLACES FROM MARLOWS',
                'description' => NULL,
                'image_url' => 'Category/1650348971-1280x375engagement-rings-banner.png',
                'enable_filter' => 0,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => 'Diamond Necklaces | Certified Diamond Jewellery | GIA Certified Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse the stunning collection of diamonds necklaces. Whether it is for you or your loved ones, you&#039;ll love our range of certified diamonds necklaces.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:27:09',
                'updated_at' => '2022-05-11 11:37:19',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Pendants',
                'title' => 'CERTIFIED DIAMOND PENDANTS',
                'slug' => 'pendants',
                'parent_id' => 2,
                'short_description' => 'STUNNING DIAMOND PENDANTS ONLINE',
                'description' => NULL,
                'image_url' => 'Category/1650348971-1280x375engagement-rings-banner.png',
                'enable_filter' => 0,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => 'Certified Diamond Pendants | Diamond Jewellery | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Gift your loved ones with a certified diamond pendants. View our wide collection of handcrafted diamond pendants, a perfect addition to a range of necklaces',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:33:59',
                'updated_at' => '2022-05-11 11:38:26',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'Engagement Rings',
                'title' => 'Engagement Rings',
                'slug' => 'engagement-rings',
                'parent_id' => 0,
                'short_description' => '',
                'description' => NULL,
                'image_url' => 'Category/1650350426-1280x375MarlowsDiamonds-Blog-Header-1.jpg',
                'enable_filter' => 1,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => 'Customised Rings for Women : Marlow\'s Diamond-A GIA certified company',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Engagement Rings Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:40:26',
                'updated_at' => '2023-05-17 09:43:06',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'Halo',
                'title' => 'HALO DIAMOND ENGAGEMENT RINGS',
                'slug' => 'halo',
                'parent_id' => 8,
                'short_description' => 'AVAILABLE IN A VARIETY OF CUTS AND STYLES',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 2,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/halo.png',
                'meta_title' => 'Halo Diamond Engagement Rings Online |GIA Certified Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Discover a beautiful range of halo engagement rings at Marlows Diamonds for the perfect token of love for your life partner. Whatsapp us today to find your dream within budget.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:44:27',
                'updated_at' => '2023-05-17 10:14:28',
            ),
            8 => 
            array (
                'id' => 10,
                'name' => 'Cushion',
                'title' => 'CUSHION CUT',
                'slug' => 'halo-cushion',
                'parent_id' => 9,
                'short_description' => '<p>HALO SETTING<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 8,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/cushion.png',
                'meta_title' => 'CUSHION CUT | Halo Diamond Engagement rings',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Cushion Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:45:20',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            9 => 
            array (
                'id' => 11,
                'name' => 'Emerald',
                'title' => 'EMERALD CUT',
                'slug' => 'emerald',
                'parent_id' => 9,
                'short_description' => '<p>HALO SETTING<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 3,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/emerald.png',
                'meta_title' => 'Emerald Cut Diamond Rings | Halo Setting | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Emerald cut diamond rings in a Halo setting. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:47:59',
                'updated_at' => '2022-05-11 11:18:24',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'Heart',
                'title' => 'HEART CUT DIAMOND',
                'slug' => 'heart',
                'parent_id' => 9,
                'short_description' => '<p>HALO SETTING RING<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 7,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/heart.png',
                'meta_title' => 'Heart Cut Diamond Rings | Halo Setting | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Heart cut diamond rings in a Halo setting. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:50:20',
                'updated_at' => '2022-05-11 11:15:56',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'Marquise',
                'title' => 'MARQUISE CUT DIAMOND',
                'slug' => 'marquise',
                'parent_id' => 9,
                'short_description' => 'HALO SETTING ENGAGEMENT RINGS',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 5,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/marquee.png',
                'meta_title' => 'Marquise Cut Diamond | Halo Setting | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Marquise cut diamond rings in a Halo setting. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:51:17',
                'updated_at' => '2022-05-11 11:14:15',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'Oval',
                'title' => 'OVAL CUT HALO DIAMOND',
                'slug' => 'oval',
                'parent_id' => 9,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 4,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/oval.png',
                'meta_title' => 'Halo Diamond Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Oval cut Halo diamond rings. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:52:27',
                'updated_at' => '2022-05-11 11:12:43',
            ),
            13 => 
            array (
                'id' => 15,
                'name' => 'Pear',
                'title' => 'PEAR CUT',
                'slug' => 'pear',
                'parent_id' => 9,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 6,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/pear.png',
                'meta_title' => 'Pear Cut | Halo Diamond Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Pear cut diamond rings with Halo setting. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:53:31',
                'updated_at' => '2022-05-11 11:11:23',
            ),
            14 => 
            array (
                'id' => 16,
                'name' => 'Princess',
                'title' => 'HALO PRINCESS RINGS',
                'slug' => 'princess-halo-rings',
                'parent_id' => 9,
                'short_description' => '<p>GET BIGGER DIAMONDS CHEAPER<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 2,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/priceless.png',
                'meta_title' => 'Princess Cut Diamond Rings | Halo Setting | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Princess cut diamond rings in a Halo setting. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:54:26',
                'updated_at' => '2022-05-11 11:06:33',
            ),
            15 => 
            array (
                'id' => 17,
                'name' => 'Round',
                'title' => 'HALO ROUND RINGS',
                'slug' => 'halo-round',
                'parent_id' => 9,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 1,
                'active_icon' => '/Categories/round.png',
                'hover_icon' => '/Categories/round.png',
                'meta_title' => 'Round Cut Diamond Ring | Halo Setting | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut diamond rings in a Halo setting. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 06:55:59',
                'updated_at' => '2022-05-11 11:04:53',
            ),
            16 => 
            array (
                'id' => 18,
                'name' => 'Multi-Stone',
                'title' => 'TRILOGY ENGAGEMENT RINGS',
                'slug' => 'multi-stone',
                'parent_id' => 8,
                'short_description' => 'CERTIFIED DIAMOND ENAGEMENT RINGS BIRMINGHAM',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 4,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/multistone.png',
                'meta_title' => 'Mutli-Stone Diamond Rings | Certified Trilogy Four &amp; Five Stone Diamond Rings',
                'meta_keyword' => NULL,
                'meta_description' => 'Explore our stunning range of GIA certified multi stone diamond rings as perfect as your partner. All of our diamond engagement rings are ethically sourced &amp; certified.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 07:10:12',
                'updated_at' => '2022-05-11 11:42:19',
            ),
            17 => 
            array (
                'id' => 19,
                'name' => 'Cushion',
                'title' => 'CUSHION CUT',
                'slug' => 'multi-stone-cushion',
                'parent_id' => 18,
                'short_description' => 'MULTI-STONE SETTING',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 8,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/cushion.png',
                'meta_title' => 'CUSHION CUT | Multi-Stone Diamond Engagement rings',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Cushion Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 07:12:25',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            18 => 
            array (
                'id' => 20,
                'name' => 'Emerald',
                'title' => 'EMERALD MULTI STONE RINGS',
                'slug' => 'emerald-multi-stone-rings',
                'parent_id' => 18,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 3,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/emerald.png',
                'meta_title' => 'Emerald Archives - Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Emerald Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 07:20:35',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            19 => 
            array (
                'id' => 21,
                'name' => 'Heart',
                'title' => 'HEART MULTI STONE RINGS',
                'slug' => 'heart-multi-stone-rings',
                'parent_id' => 18,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 7,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/heart.png',
                'meta_title' => 'Heart Archives - Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Heart Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 07:26:08',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            20 => 
            array (
                'id' => 22,
                'name' => 'Marquise',
                'title' => 'MARQUISE MULTI STONE RINGS',
                'slug' => 'marquise-multi-stone-rings',
                'parent_id' => 18,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 5,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/marquee.png',
                'meta_title' => 'Marquise Cut | Multi-Stone Diamond Engagement rings',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Marquise Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 07:29:09',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            21 => 
            array (
                'id' => 23,
                'name' => 'Oval',
                'title' => 'OVAL MULTI STONE RINGS',
                'slug' => 'oval-multi-stone-rings',
                'parent_id' => 18,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 4,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/oval.png',
                'meta_title' => 'Oval Cut | Multi-Stone Diamond Engagement rings',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Oval Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 07:30:20',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            22 => 
            array (
                'id' => 24,
                'name' => 'Pear',
                'title' => 'PEAR MULTI STONE RINGS',
                'slug' => 'pear-multi-stone-rings',
                'parent_id' => 18,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 6,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/pear.png',
                'meta_title' => 'Pear Archives - Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Pear Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 07:30:58',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            23 => 
            array (
                'id' => 25,
                'name' => 'Princess',
                'title' => 'PRINCESS MULTI STONE RINGS',
                'slug' => 'princess-multi-stone-rings',
                'parent_id' => 18,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 2,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/priceless.png',
                'meta_title' => 'Princess Archives - Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Princess Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:38:55',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            24 => 
            array (
                'id' => 26,
                'name' => 'Round',
                'title' => 'ROUND CUT DIAMONDS',
                'slug' => 'halo-round-1',
                'parent_id' => 18,
                'short_description' => 'CERTIFIED DIAMOND ENGAGEMENT RINGS',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 1,
                'active_icon' => '/Categories/round.png',
                'hover_icon' => '/Categories/round.png',
                'meta_title' => 'Round Cut Multi Stone | Diamond Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of round cut multi stone diamond rings. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:40:14',
                'updated_at' => '2022-05-10 19:11:13',
            ),
            25 => 
            array (
                'id' => 27,
                'name' => 'Shoulder Set',
                'title' => 'SHOULDER SET DIAMOND ENGAGEMENT RINGS',
                'slug' => 'shoulder-set',
                'parent_id' => 8,
                'short_description' => 'AVAILABLE IN A VARIETY OF CUTS AND STYLES',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 3,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/shoulder-1.png',
                'meta_title' => 'Shoulder Set Diamond Engagement Rings | GIA Certified Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'If you are looking for something classic and elegant, then our forever classic shoulder set diamond rings is the right one for you and adds extra sparkle to your diamond engagement rings.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:41:23',
                'updated_at' => '2022-05-11 11:43:20',
            ),
            26 => 
            array (
                'id' => 28,
                'name' => 'Cushion',
                'title' => 'CUSHION CUT',
                'slug' => 'shoulder-cushion',
                'parent_id' => 27,
                'short_description' => 'SHOULDER SET SETTING',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 8,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/cushion.png',
                'meta_title' => 'CUSHION CUT | Shoulder Set Diamond Engagement rings',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Cushion Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:42:27',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            27 => 
            array (
                'id' => 29,
                'name' => 'Emerald',
                'title' => 'EMERALD SHAPED DIAMOND',
                'slug' => 'emerald-shoulder-rings',
                'parent_id' => 27,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 3,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/emerald.png',
                'meta_title' => 'Emerald Cut Diamond Rings | Shoulder Setting | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Emerald shaped diamond in a Shoulder set ring. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:44:02',
                'updated_at' => '2022-05-10 19:09:11',
            ),
            28 => 
            array (
                'id' => 30,
                'name' => 'Heart',
                'title' => 'HEART SHAPED DIAMOND',
                'slug' => 'heart-shoulder-rings',
                'parent_id' => 27,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 7,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/heart.png',
                'meta_title' => 'Heart Cut Diamond | Shoulder Set Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Heart shaped diamonds in a Shoulder setting ring. Stunning certified diamond rings available online and in-store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:45:46',
                'updated_at' => '2022-05-10 19:07:19',
            ),
            29 => 
            array (
                'id' => 31,
                'name' => 'Marquise',
                'title' => 'MARQUISE CUT DIAMOND',
                'slug' => 'marquise-shoulder-rings',
                'parent_id' => 27,
                'short_description' => '<p>SHOULDER SET ENGAGEMENT RINGS<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 5,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/marquee.png',
                'meta_title' => 'Marquise Cut Diamond | Shoulder Setting Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Marquise cut diamonds in Shoulder setting rings. Stunning certified diamond rings are available online and in-store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:46:29',
                'updated_at' => '2022-05-10 19:05:56',
            ),
            30 => 
            array (
                'id' => 32,
                'name' => 'Oval',
                'title' => 'OVAL CUT DIAMOND',
                'slug' => 'oval-shoulder-rings',
                'parent_id' => 27,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 4,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/oval.png',
                'meta_title' => 'Oval Cut Diamond | Shoulder Setting Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Oval cut diamonds in a Shoulder setting ring. Stunning certified diamond rings are available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:47:29',
                'updated_at' => '2022-05-10 19:04:17',
            ),
            31 => 
            array (
                'id' => 33,
                'name' => 'Pear',
                'title' => 'PEAR CUT DIAMOND',
                'slug' => 'pear-shoulder-rings',
                'parent_id' => 27,
                'short_description' => '<p>SHOULDER SET ENGAGEMENT RINGS<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 6,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/pear.png',
                'meta_title' => 'Pear Cut Diamond Rings | Shoulder Setting Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Pear shaped diamonds in a Shoulder setting ring. Stunning certified diamond rings are available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:48:25',
                'updated_at' => '2022-05-10 19:03:16',
            ),
            32 => 
            array (
                'id' => 34,
                'name' => 'Princess',
                'title' => 'PRINCESS SHAPED DIAMOND',
                'slug' => 'princess-shoulder-rings',
                'parent_id' => 27,
                'short_description' => 'SHOULDER SET ENGAGEMENT RINGS',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 2,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/priceless.png',
                'meta_title' => 'Princess Cut Diamond Rings | Shoulder Setting Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Princess shaped diamonds in a Shoulder set ring. Stunning certified diamond rings are available online and in-store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:50:02',
                'updated_at' => '2022-05-10 19:01:54',
            ),
            33 => 
            array (
                'id' => 35,
                'name' => 'Round',
                'title' => 'ROUND CUT DIAMOND',
                'slug' => 'round-shoulder-rings',
                'parent_id' => 27,
                'short_description' => 'SHOULDER SET ENGAGEMENT RINGS',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 1,
                'active_icon' => '/Categories/round.png',
                'hover_icon' => '/Categories/round.png',
                'meta_title' => 'Round Shaped Cut Diamond | Shoulder Setting | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round shaped cut diamond in a Shoulder set ring. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:50:58',
                'updated_at' => '2022-05-10 18:58:55',
            ),
            34 => 
            array (
                'id' => 36,
                'name' => 'Solitaire',
                'title' => 'CLASSIC STYLE DIAMOND ENGAGEMENT RINGS',
                'slug' => 'solitaire',
                'parent_id' => 8,
                'short_description' => '<p>AVAILABLE IN A VARIETY OF CUTS AND STYLES<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 1,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/solitaire.png',
                'meta_title' => 'Solitaire Diamond Engagement Rings | Tiffany Style Diamond Engagement Rings',
                'meta_keyword' => NULL,
                'meta_description' => 'Find a complete range of round brilliant cut solitaire diamond engagement rings at Marlows Diamonds. We only provide the most stunning, exquisite rings for your partner to cherish forever.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 08:51:42',
                'updated_at' => '2022-05-11 11:40:04',
            ),
            35 => 
            array (
                'id' => 37,
                'name' => 'Cushion',
                'title' => 'CUSHION CUT',
                'slug' => 'solitaire-cushion',
                'parent_id' => 36,
                'short_description' => 'SOLITAIRE SETTING',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 8,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/cushion.png',
                'meta_title' => 'CUSHION CUT | Solitaire Diamond Engagement rings',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Cushion Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:04:50',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            36 => 
            array (
                'id' => 38,
                'name' => 'Emerald',
                'title' => 'EMERALD CUT SOLITAIRE DIAMOND',
                'slug' => 'emerald-plain-rings',
                'parent_id' => 36,
                'short_description' => 'CERTIFIED DIAMOND ENGAGEMENT RINGS',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 3,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/emerald.png',
                'meta_title' => 'Emerald cut Solitaire Engagement Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Emerald cut Solitaire plain diamond rings. Stunning certified diamond rings are available online and in-store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:10:45',
                'updated_at' => '2022-05-10 18:54:00',
            ),
            37 => 
            array (
                'id' => 39,
                'name' => 'Heart',
                'title' => 'HEART SHAPED SOLITAIRE DIAMOND',
                'slug' => 'heart-plain-rings',
                'parent_id' => 36,
                'short_description' => 'CERTIFIED DIAMOND ENGAGEMENT RINGS',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 7,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/heart.png',
                'meta_title' => 'Heart Shaped Cut Solitaire | Certified Plain Diamond Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Heart shaped Cut Solitaire plain diamond rings. Stunning certified diamond rings available online and in-store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:11:52',
                'updated_at' => '2022-05-10 18:51:58',
            ),
            38 => 
            array (
                'id' => 40,
                'name' => 'Marquise',
                'title' => 'MARQUISE CUT SOLITAIRE DIAMOND',
                'slug' => 'marquise-plain-rings',
                'parent_id' => 36,
                'short_description' => 'CERTIFIED DIAMOND ENGAGEMENT RINGS',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 5,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/marquee.png',
                'meta_title' => 'Marquise Cut | Plain Diamond Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Marquise cut plain diamond rings. Stunning certified diamond rings are available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:12:39',
                'updated_at' => '2022-05-10 18:47:48',
            ),
            39 => 
            array (
                'id' => 41,
                'name' => 'Oval',
                'title' => 'OVAL CUT SOLITAIRE DIAMOND',
                'slug' => 'oval-plain-rings',
                'parent_id' => 36,
                'short_description' => 'CERTIFIED DIAMOND ENGAGEMENT RINGS',
                'description' => '<div class="category-page-content" style="background: #f2f2f7;border-radius: 20px;padding: 25px 40px;width: 100%;"> 
<h2 style="margin: 0 0px 15px !important; text-align: center; margin-top: 0pt; margin-bottom: 0pt; line-height: 33pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
<span style=" color: rgb(13, 9, 0); font-size: 24pt;">Oval Cut Engagement Rings from Marlows</span>
<span style=" color: rgb(13, 9, 0); font-size: 24pt;">
<o:p></o:p>
</span>
</h2>
<p class="17" style="margin-top: 0pt; margin-bottom: 18pt; line-height: 18pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
<span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">Our Oval shape loose diamond selection in stock is well appreciated all over the UK and beyond. Oval shape diamonds are the second largest seller of diamond shapes at Marlows. We buy the best quality rough diamonds and our specialist polishers and cutters bring the best of this shape in every diamond they polish for us. </span>
<span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">
<o:p></o:p>
</span>
</p>
<p class="17" style="margin-top: 0pt; margin-bottom: 18pt; line-height: 18pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
<font color="#0d0900"><span style="font-size: 10.5pt;">Unknowing customers come to us every day looking for an “Excellent Cut” oval. What they don’t </span><span style="font-size: 14px;">realize</span><span style="font-size: 10.5pt;">&nbsp;is that the GIA does not specify a “Cut” grade for oval shape diamonds. We are diamond dealers and our expertise go beyond the GIA. We concentrate on oval shape ratios, table, and depth far more than the Cut polish and Symmetry graded by the GIA.</span></font>
<span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">
<o:p></o:p>
</span>
</p>
<p class="17" style="margin-top: 0pt; margin-bottom: 18pt; line-height: 18pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
<span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">All you have to look at is our ovals and any other ovals “online” you see the difference. For eg, our 1ct oval will visually appear like any online 1.20ct oval, our 1.50ct as any other 2ct. You can be confident to choose ovals from us in the knowledge that your oval will most definitely look much bigger than any other jewellers for the same price. £2000 spend on our ovals will give you an equivalent appearance of £3000 from any other jeweller. </span>
<span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">
<o:p></o:p>
</span>
</p>
<p class="17" style="margin-top: 0pt; margin-bottom: 18pt; line-height: 18pt; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">
<span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">As with our </span><a href="/product-category/engagement-rings/solitaire/emerald-plain-rings"><u><span class="16" style=" color: rgb(128, 0, 128); font-size: 10.5pt;">Emerald</span></u></a><span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">&nbsp;</span><a href="https://marlows-diamonds.co.uk/product-category/engagement-rings/solitaire/pear-plain-rings"><u><span class="15" style=" color: rgb(13, 9, 0); font-size: 10.5pt;">pear</span></u></a><span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">&nbsp;or&nbsp;</span><a href="/product-category/engagement-rings/solitaire/marquise-plain-rings"><u><span class="15" style=" color: rgb(13, 9, 0); font-size: 10.5pt;">marquise shape diamond rings</span></u></a><span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">, an oval diamond ring will also help make the wearer’s finger longer and slender with the right ratios, especially when set in a classic&nbsp;</span><a href="/product-category/engagement-rings/solitaire/oval-plain-rings"><u><span class="15" style=" color: rgb(13, 9, 0); font-size: 10.5pt;">solitaire design</span></u></a><span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">.&nbsp;</span><a href="/product-category/engagement-rings/halo"><u><span class="15" style=" color: rgb(13, 9, 0); font-size: 10.5pt;">Halo rings</span></u></a><font color="#0d0900"><span style="font-size: 10.5pt;">&nbsp;also suit this shape by surrounding your </span><span style="font-size: 14px;">center</span><span style="font-size: 10.5pt;">&nbsp;stone with elegantly micro set round diamonds.</span></font>
<span style="mso-spacerun:\'yes\';
color:rgb(13,9,0);font-size:10.5000pt;">
<o:p></o:p>
</span>
</p>
<p class="MsoNormal"><span style="mso-spacerun:\'yes\';color:rgb(13,9,0);
font-size:10.5000pt;">All our oval diamond rings can be produced in platinum 950, 18k Yellow Gold, and 18k Rose Gold depending on your skin tone. Speak to one of our specialists on 01212364415. With over 400 oval shape diamonds in stock, yours is waiting to be picked out</span></p>

</div>',
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 4,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/oval.png',
                'meta_title' => 'Oval Cut | Plain Diamond Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Oval cut plain diamond rings. Stunning certified diamond rings are available online and in-store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:13:27',
                'updated_at' => '2022-12-16 18:24:10',
            ),
            40 => 
            array (
                'id' => 42,
                'name' => 'Pear',
                'title' => 'PEAR CUT SOLITAIRE DIAMOND',
                'slug' => 'pear-plain-rings',
                'parent_id' => 36,
                'short_description' => '<p>CERTIFIED DIAMOND ENGAGEMENT RINGS<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 6,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/pear.png',
                'meta_title' => 'Pear Cut plain Diamond Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Pear cut plain solitaire diamond rings. Stunning certified diamond rings are available online and in-store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:14:16',
                'updated_at' => '2022-05-10 18:43:42',
            ),
            41 => 
            array (
                'id' => 43,
                'name' => 'Princess',
                'title' => 'PRINCESS CUT SOLITAIRE DIAMOND',
                'slug' => 'princess-plain-rings',
                'parent_id' => 36,
                'short_description' => '<p>CERTIFIED DIAMOND ENGAGEMENT RINGS<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 2,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/priceless.png',
                'meta_title' => 'Princess Cut Solitaire | Plain Diamond Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Princess cut solitaire plain diamond rings. Stunning certified diamond rings are available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:15:37',
                'updated_at' => '2022-05-10 18:41:23',
            ),
            42 => 
            array (
                'id' => 44,
                'name' => 'Round',
                'title' => 'ROUND CUT SOLITAIRE DIAMOND',
                'slug' => 'round-plain-rings',
                'parent_id' => 36,
                'short_description' => '<p>CERTIFIED DIAMOND ENGAGEMENT RINGS<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 1,
                'active_icon' => '/Categories/round.png',
                'hover_icon' => '/Categories/round.png',
                'meta_title' => 'Round Cut | Solitaire Diamond Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Solitaire diamond rings. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:16:26',
                'updated_at' => '2022-05-10 18:39:29',
            ),
            43 => 
            array (
                'id' => 45,
                'name' => 'Eternity Rings',
                'title' => 'DIAMOND SET WEDDING RINGS ONLINE',
                'slug' => 'eternity-rings',
                'parent_id' => 0,
                'short_description' => '<p>PERFECT DIAMOND WEDDING RING <br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 0,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => 'Diamond Set Wedding Rings | Eternity Rings Online',
                'meta_keyword' => NULL,
                'meta_description' => 'Shop the beautiful collection of Diamond Eternity Rings to buy online at Marlows Diamonds. Buy online now or stop by one of our Jewellery stores today.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:17:26',
                'updated_at' => '2022-05-11 12:23:44',
            ),
            44 => 
            array (
                'id' => 46,
                'name' => 'Diamond',
                'title' => 'ETERNITY DIAMOND RINGS',
                'slug' => 'diamond',
                'parent_id' => 45,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 0,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => 'Diamond Archives - Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of Round cut Diamond Stunning certified diamond rings available online and in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:19:12',
                'updated_at' => '2023-02-22 11:11:05',
            ),
            45 => 
            array (
                'id' => 47,
                'name' => 'Wedding / Eternity Rings',
                'title' => 'WEDDING / ETERNITY RINGS ONLINE',
                'slug' => 'wedding-rings',
                'parent_id' => 0,
                'short_description' => 'STUNNING WEDDING BANDS &amp; DIAMOND ETERNITY RINGS',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => 'Diamond Wedding and Eternity Rings Online | Marlow’s Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Marlow’s Diamond houses a wide range of eternity rings to choose from. Shop eternity rings online or from our stores in London and Birmingham with the best offers.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:20:11',
                'updated_at' => '2023-05-17 10:34:10',
            ),
            46 => 
            array (
                'id' => 48,
                'name' => 'Mens',
                'title' => 'MENS WEDDING RINGS',
                'slug' => 'mens',
                'parent_id' => 47,
                'short_description' => 'PLAIN &amp; DIAMOND SET ETERNITY RINGS FOR MEN',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 1,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/mens_diamond.png',
                'meta_title' => 'Plain &amp; Diamond Set Wedding Rings for Men | GIA Certified Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Plain wedding rings and diamond wedding bands for men handcrafted by the jewellery experts at Marlows. Browse mens wedding rings online or in store.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:20:56',
                'updated_at' => '2023-05-17 10:41:15',
            ),
            47 => 
            array (
                'id' => 49,
                'name' => 'Diamond Band',
                'title' => 'DIAMOND SET MENS WEDDING RINGS',
                'slug' => 'diamond-band',
                'parent_id' => 48,
                'short_description' => '',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 2,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/mens_diamond.png',
                'meta_title' => 'Mens Diamond Band Wedding Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning range of mens diamond set wedding bands and eternity rings. Stunning certified diamond rings available online and in store',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:21:37',
                'updated_at' => '2022-05-11 11:28:42',
            ),
            48 => 
            array (
                'id' => 50,
                'name' => 'Plain Band',
                'title' => 'PLAIN MENS WEDDING RINGS',
                'slug' => 'plain-band',
                'parent_id' => 48,
                'short_description' => '<p>GET BIGGER DIAMONDS CHEAPER<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 1,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/plain.png',
                'meta_title' => 'Mens Plain Band Wedding Rings | GIA Certified Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our exclusive collection of mens plain wedding rings, handcrafted by the jewellery experts at Marlows. Call us today to buy our stunning range of mens wedding rings online or pop into our stores.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:22:24',
                'updated_at' => '2022-05-11 11:25:24',
            ),
            49 => 
            array (
                'id' => 51,
                'name' => 'Womens',
                'title' => 'WOMENS WEDDING RINGS',
                'slug' => 'womens',
                'parent_id' => 47,
                'short_description' => '<p>PLAIN AND DIAMOND SET ETERNITY WEDDING RINGS<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 2,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/womens_diamond.png',
                'meta_title' => 'Womens Wedding Rings | Diamond Set Eternity Rings | Marlows Diamonds',
                'meta_keyword' => NULL,
                'meta_description' => 'Exquisite womens wedding &amp; eternity rings, handcrafted by passionate jewellery experts. Shop a classic range of wedding rings online or in store today.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:23:43',
                'updated_at' => '2022-05-11 11:44:42',
            ),
            50 => 
            array (
                'id' => 52,
                'name' => 'Diamond Band',
                'title' => 'WOMENS WEDDING RINGS',
                'slug' => 'diamond-band-womens',
                'parent_id' => 51,
                'short_description' => '',
                'description' => '<h2 class="vc_custom_heading">Mark Your Love with Spellbinding Eternity Rings for Women<br></h2><p class="vc_custom_heading">Sure you got down on one knee to ask her 
hand in marriage but love demands regular reminders and what better way 
to show it than with diamonds? As De Beers once said, “Diamonds are 
Forever”. On your coming anniversary, give your better half the 
everlasting gift of love with Marlow’s range of eternity rings for 
women. But what are eternity rings you ask? Eternity rings are bands of 
precious metal (gold or platinum) set with a continuous line of 
identical diamonds that symbolize everlasting love. Even though nowadays
eternity rings only comprise of diamonds on the front where the ring is
visible but the emotion behind remains the same. Eternity rings were 
introduced to mark years of love, commitment, and effort put into a 
marriage. Why not dedicate this forever band to the love of your life 
this wedding anniversary and tell her how precious she is to you?</p>
<h2>Buy GIA Graded Conflict-Free Eternity Rings for Women</h2>
<p class="vc_custom_heading">Marlow’s Diamonds began with the vision of 
bringing diamonds to the masses through an online platform without 
compromising on quality. This is why all our diamonds are ethically 
sourced and graded by the GIA so you can be assured that the eternity 
rings for women on our website are all made from the highest quality 
gemstones. We offer full and half eternity rings that you can also buy 
for your wedding after all that is the one day where you must pamper the
lady you love with the very best. Our range of eternity rings for women
consists of various styles, from plain gold and platinum bands to full 
diamond set rings in some of the most stunning, unqiue designs.</p><p></p>',
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 2,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/womens_diamond.png',
                'meta_title' => 'Womens Diamond Band Wedding Rings | Womens Diamond Wedding Rings',
                'meta_keyword' => NULL,
                'meta_description' => 'Explore our large collection of womens diamond bands handcrafted by jewellery experts at Marlows. Buy our studding range of womens diamond wedding rings.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:24:35',
                'updated_at' => '2022-05-13 13:02:28',
            ),
            51 => 
            array (
                'id' => 53,
                'name' => 'Plain Band',
                'title' => 'PLAIN WOMENS WEDDING RINGS',
                'slug' => 'plain-band-womens',
                'parent_id' => 51,
                'short_description' => '<p>GET BIGGER DIAMONDS CHEAPER<br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 1,
                'sort_order' => 1,
                'active_icon' => NULL,
                'hover_icon' => '/Categories/plain.png',
                'meta_title' => 'Womens Plain Band Wedding Rings | Women Eternity Rings Online',
                'meta_keyword' => NULL,
                'meta_description' => 'Browse our stunning collection of womens plain band wedding rings handcrafted by jewellery experts. Buy our stunning range of womens diamond wedding rings online or visit our stores.',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-04-19 09:25:15',
                'updated_at' => '2022-05-11 11:21:47',
            ),
            52 => 
            array (
                'id' => 54,
                'name' => 'Exclusive to Marlows',
                'title' => '<span class="exclusive-heading">Exclusive to Marlows<span>',
                'slug' => 'exclusive-to-marlows',
                'parent_id' => 2,
                'short_description' => '<p><b>Exclusive to Marlows | Exclusive to Marlows rings</b><br></p>',
                'description' => NULL,
                'image_url' => NULL,
                'enable_filter' => 0,
                'sort_order' => NULL,
                'active_icon' => NULL,
                'hover_icon' => NULL,
                'meta_title' => 'Exclusive to Marlows',
                'meta_keyword' => 'Exclusive to Marlows',
                'meta_description' => 'Exclusive to Marlows | Exclusive to Marlows rings',
                'status' => 1,
                'is_category_page' => 0,
                'is_deleted' => 0,
                'created_at' => '2022-10-31 17:32:59',
                'updated_at' => '2022-10-31 17:32:59',
            ),
        ));
        
        
    }
}