<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::truncate();

        $countries = [
            ['name' => 'Afghanistan', 'shortname' => 'AF', 'phonecode'=> '93'],
            ['name' => 'Albania', 'shortname' => 'AL', 'phonecode'=> '355'],
            ['name' => 'Algeria', 'shortname' => 'DZ', 'phonecode'=> '213'],
            ['name' => 'American Samoa', 'shortname' => 'AS', 'phonecode'=> '1684'],
            ['name' => 'Andorra', 'shortname' => 'AD', 'phonecode'=> '376'],
            ['name' => 'Angola', 'shortname' => 'AO', 'phonecode'=> '244'],
            ['name' => 'Anguilla', 'shortname' => 'AI', 'phonecode'=> '1264'],
            ['name' => 'Antarctica', 'shortname' => 'AQ', 'phonecode'=> '0'],
            ['name' => 'Antigua And Barbuda', 'shortname' => 'AG', 'phonecode'=> '1268'],
            ['name' => 'Argentina', 'shortname' => 'AR', 'phonecode'=> '54'],
            ['name' => 'Armenia', 'shortname' => 'AM', 'phonecode'=> '374'],
            ['name' => 'Aruba', 'shortname' => 'AW', 'phonecode'=> '297'],
            ['name' => 'Australia', 'shortname' => 'AU', 'phonecode'=> '61'],
            ['name' => 'Austria', 'shortname' => 'AT', 'phonecode'=> '43'],
            ['name' => 'Azerbaijan', 'shortname' => 'AZ', 'phonecode'=> '994'],
            ['name' => 'Bahamas The', 'shortname' => 'BS', 'phonecode'=> '1242'],
            ['name' => 'Bahrain', 'shortname' => 'BH', 'phonecode'=> '973'],
            ['name' => 'Bangladesh', 'shortname' => 'BD', 'phonecode'=> '880'],
            ['name' => 'Barbados', 'shortname' => 'BB', 'phonecode'=> '1246'],
            ['name' => 'Belarus', 'shortname' => 'BY', 'phonecode'=> '375'],
            ['name' => 'Belgium', 'shortname' => 'BE', 'phonecode'=> '32'],
            ['name' => 'Belize', 'shortname' => 'BZ', 'phonecode'=> '501'],
            ['name' => 'Benin', 'shortname' => 'BJ', 'phonecode'=> '229'],
            ['name' => 'Bermuda', 'shortname' => 'BM', 'phonecode'=> '1441'],
            ['name' => 'Bhutan', 'shortname' => 'BT', 'phonecode'=> '975'],
            ['name' => 'Bolivia', 'shortname' => 'BO', 'phonecode'=> '591'],
            ['name' => 'Bosnia and Herzegovina', 'shortname' => 'BA', 'phonecode'=> '387'],
            ['name' => 'Botswana', 'shortname' => 'BW', 'phonecode'=> '267'],
            ['name' => 'Bouvet Island', 'shortname' => 'BV', 'phonecode'=> '0'],
            ['name' => 'Brazil', 'shortname' => 'BR', 'phonecode'=> '55'],
            ['name' => 'British Indian Ocean Territory', 'shortname' => 'IO', 'phonecode'=> '246'],
            ['name' => 'Brunei', 'shortname' => 'BN', 'phonecode'=> '673'],
            ['name' => 'Bulgaria', 'shortname' => 'BG', 'phonecode'=> '359'],
            ['name' => 'Burkina Faso', 'shortname' => 'BF', 'phonecode'=> '226'],
            ['name' => 'Burundi', 'shortname' => 'BI', 'phonecode'=> '257'],
            ['name' => 'Cambodia', 'shortname' => 'KH', 'phonecode'=> '855'],
            ['name' => 'Cameroon', 'shortname' => 'CM', 'phonecode'=> '237'],
            ['name' => 'Canada', 'shortname' => 'CA', 'phonecode'=> '1'],
            ['name' => 'Cape Verde', 'shortname' => 'CV', 'phonecode'=> '238'],
            ['name' => 'Cayman Islands', 'shortname' => 'KY', 'phonecode'=> '1345'],
            ['name' => 'Central African Republic', 'shortname' => 'CF', 'phonecode'=> '236'],
            ['name' => 'Chad', 'shortname' => 'TD', 'phonecode'=> '235'],
            ['name' => 'Chile', 'shortname' => 'CL', 'phonecode'=> '56'],
            ['name' => 'China', 'shortname' => 'CN', 'phonecode'=> '86'],
            ['name' => 'Christmas Island', 'shortname' => 'CX', 'phonecode'=> '61'],
            ['name' => 'Cocos (Keeling) Islands', 'shortname' => 'CC', 'phonecode'=> '672'],
            ['name' => 'Colombia', 'shortname' => 'CO', 'phonecode'=> '57'],
            ['name' => 'Comoros', 'shortname' => 'KM', 'phonecode'=> '269'],
            ['name' => 'Republic Of The Congo', 'shortname' => 'CG', 'phonecode'=> '242'],
            ['name' => 'Democratic Republic Of The Congo', 'shortname' => 'CD', 'phonecode'=> '242'],
            ['name' => 'Cook Islands', 'shortname' => 'CK', 'phonecode'=> '682'],
            ['name' => 'Costa Rica', 'shortname' => 'CR', 'phonecode'=> '506'],
            ['name' => 'Cote D Ivoire (Ivory Coast)', 'shortname' => 'CI', 'phonecode'=> '225'],
            ['name' => 'Croatia (Hrvatska)', 'shortname' => 'HR', 'phonecode'=> '385'],
            ['name' => 'Cuba', 'shortname' => 'CU', 'phonecode'=> '53'],
            ['name' => 'Cyprus', 'shortname' => 'CY', 'phonecode'=> '357'],
            ['name' => 'Czech Republic', 'shortname' => 'CZ', 'phonecode'=> '420'],
            ['name' => 'Denmark', 'shortname' => 'DK', 'phonecode'=> '45'],
            ['name' => 'Djibouti', 'shortname' => 'DJ', 'phonecode'=> '253'],
            ['name' => 'Dominica', 'shortname' => 'DM', 'phonecode'=> '1767'],
            ['name' => 'Dominican Republic', 'shortname' => 'DO', 'phonecode'=> '1809'],
            ['name' => 'East Timor', 'shortname' => 'TP', 'phonecode'=> '670'],
            ['name' => 'Ecuador', 'shortname' => 'EC', 'phonecode'=> '593'],
            ['name' => 'Egypt', 'shortname' => 'EG', 'phonecode'=> '20'],
            ['name' => 'El Salvador', 'shortname' => 'SV', 'phonecode'=> '503'],
            ['name' => 'Equatorial Guinea', 'shortname' => 'GQ', 'phonecode'=> '240'],
            ['name' => 'Eritrea', 'shortname' => 'ER', 'phonecode'=> '291'],
            ['name' => 'Estonia', 'shortname' => 'EE', 'phonecode'=> '372'],
            ['name' => 'Ethiopia', 'shortname' => 'ET', 'phonecode'=> '251'],
            ['name' => 'External Territories of Australia', 'shortname' => 'XA', 'phonecode'=> '61'],
            ['name' => 'Falkland Islands', 'shortname' => 'FK', 'phonecode'=> '500'],
            ['name' => 'Faroe Islands', 'shortname' => 'FO', 'phonecode'=> '298'],
            ['name' => 'Fiji Islands', 'shortname' => 'FJ', 'phonecode'=> '679'],
            ['name' => 'Finland', 'shortname' => 'FI', 'phonecode'=> '358'],
            ['name' => 'France', 'shortname' => 'FR', 'phonecode'=> '33'],
            ['name' => 'French Guiana', 'shortname' => 'GF', 'phonecode'=> '594'],
            ['name' => 'French Polynesia', 'shortname' => 'PF', 'phonecode'=> '689'],
            ['name' => 'French Southern Territories', 'shortname' => 'TF', 'phonecode'=> '0'],
            ['name' => 'Gabon', 'shortname' => 'GA', 'phonecode'=> '241'],
            ['name' => 'Gambia The', 'shortname' => 'GM', 'phonecode'=> '220'],
            ['name' => 'Georgia', 'shortname' => 'GE', 'phonecode'=> '995'],
            ['name' => 'Germany', 'shortname' => 'DE', 'phonecode'=> '49'],
            ['name' => 'Ghana', 'shortname' => 'GH', 'phonecode'=> '233'],
            ['name' => 'Gibraltar', 'shortname' => 'GI', 'phonecode'=> '350'],
            ['name' => 'Greece', 'shortname' => 'GR', 'phonecode'=> '30'],
            ['name' => 'Greenland', 'shortname' => 'GL', 'phonecode'=> '299'],
            ['name' => 'Grenada', 'shortname' => 'GD', 'phonecode'=> '1473'],
            ['name' => 'Guadeloupe', 'shortname' => 'GP', 'phonecode'=> '590'],
            ['name' => 'Guam', 'shortname' => 'GU', 'phonecode'=> '1671'],
            ['name' => 'Guatemala', 'shortname' => 'GT', 'phonecode'=> '502'],
            ['name' => 'Guernsey and Alderney', 'shortname' => 'XU', 'phonecode'=> '44'],
            ['name' => 'Guinea', 'shortname' => 'GN', 'phonecode'=> '224'],
            ['name' => 'Guinea-Bissau', 'shortname' => 'GW', 'phonecode'=> '245'],
            ['name' => 'Guyana', 'shortname' => 'GY', 'phonecode'=> '592'],
            ['name' => 'Haiti', 'shortname' => 'HT', 'phonecode'=> '509'],
            ['name' => 'Heard and McDonald Islands', 'shortname' => 'HM', 'phonecode'=> '0'],
            ['name' => 'Honduras', 'shortname' => 'HN', 'phonecode'=> '504'],
            ['name' => 'Hong Kong S.A.R.)', 'shortname' => 'HK', 'phonecode'=> '852'],
            ['name' => 'Hungary', 'shortname' => 'HU', 'phonecode'=> '36'],
            ['name' => 'Iceland', 'shortname' => 'IS', 'phonecode'=> '354'],
            ['name' => 'India', 'shortname' => 'IN', 'phonecode'=> '91'],
            ['name' => 'Indonesia', 'shortname' => 'ID', 'phonecode'=> '62'],
            ['name' => 'Iran', 'shortname' => 'IR', 'phonecode'=> '98'],
            ['name' => 'Iraq', 'shortname' => 'IQ', 'phonecode'=> '964'],
            ['name' => 'Ireland', 'shortname' => 'IE', 'phonecode'=> '353'],
            ['name' => 'Israel', 'shortname' => 'IL', 'phonecode'=> '972'],
            ['name' => 'Italy', 'shortname' => 'IT', 'phonecode'=> '39'],
            ['name' => 'Jamaica', 'shortname' => 'JM', 'phonecode'=> '1876'],
            ['name' => 'Japan', 'shortname' => 'JP', 'phonecode'=> '81'],
            ['name' => 'Jersey', 'shortname' => 'XJ', 'phonecode'=> '44'],
            ['name' => 'Jordan', 'shortname' => 'JO', 'phonecode'=> '962'],
            ['name' => 'Kazakhstan', 'shortname' => 'KZ', 'phonecode'=> '7'],
            ['name' => 'Kenya', 'shortname' => 'KE', 'phonecode'=> '254'],
            ['name' => 'Kiribati', 'shortname' => 'KI', 'phonecode'=> '686'],
            ['name' => 'Korea North', 'shortname' => 'KP', 'phonecode'=> '850'],
            ['name' => 'Korea South', 'shortname' => 'KR', 'phonecode'=> '82'],
            ['name' => 'Kuwait', 'shortname' => 'KW', 'phonecode'=> '965'],
            ['name' => 'Kyrgyzstan', 'shortname' => 'KG', 'phonecode'=> '996'],
            ['name' => 'Laos', 'shortname' => 'LA', 'phonecode'=> '856'],
            ['name' => 'Latvia', 'shortname' => 'LV', 'phonecode'=> '371'],
            ['name' => 'Lebanon', 'shortname' => 'LB', 'phonecode'=> '961'],
            ['name' => 'Lesotho', 'shortname' => 'LS', 'phonecode'=> '266'],
            ['name' => 'Liberia', 'shortname' => 'LR', 'phonecode'=> '231'],
            ['name' => 'Libya', 'shortname' => 'LY', 'phonecode'=> '218'],
            ['name' => 'Liechtenstein', 'shortname' => 'LI', 'phonecode'=> '423'],
            ['name' => 'Lithuania', 'shortname' => 'LT', 'phonecode'=> '370'],
            ['name' => 'Luxembourg', 'shortname' => 'LU', 'phonecode'=> '352'],
            ['name' => 'Macau S.A.R.', 'shortname' => 'MO', 'phonecode'=> '853'],
            ['name' => 'Macedonia', 'shortname' => 'MK', 'phonecode'=> '389'],
            ['name' => 'Madagascar', 'shortname' => 'MG', 'phonecode'=> '261'],
            ['name' => 'Malawi', 'shortname' => 'MW', 'phonecode'=> '265'],
            ['name' => 'Malaysia', 'shortname' => 'MY', 'phonecode'=> '60'],
            ['name' => 'Maldives', 'shortname' => 'MV', 'phonecode'=> '960'],
            ['name' => 'Mali', 'shortname' => 'ML', 'phonecode'=> '223'],
            ['name' => 'Malta', 'shortname' => 'MT', 'phonecode'=> '356'],
            ['name' => 'Man (Isle of)', 'shortname' => 'XM', 'phonecode'=> '44'],
            ['name' => 'Marshall Islands', 'shortname' => 'MH', 'phonecode'=> '692'],
            ['name' => 'Martinique', 'shortname' => 'MQ', 'phonecode'=> '596'],
            ['name' => 'Mauritania', 'shortname' => 'MR', 'phonecode'=> '222'],
            ['name' => 'Mauritius', 'shortname' => 'MU', 'phonecode'=> '230'],
            ['name' => 'Mayotte', 'shortname' => 'YT', 'phonecode'=> '269'],
            ['name' => 'Mexico', 'shortname' => 'MX', 'phonecode'=> '52'],
            ['name' => 'Micronesia', 'shortname' => 'FM', 'phonecode'=> '691'],
            ['name' => 'Moldova', 'shortname' => 'MD', 'phonecode'=> '373'],
            ['name' => 'Monaco', 'shortname' => 'MC', 'phonecode'=> '377'],
            ['name' => 'Mongolia', 'shortname' => 'MN', 'phonecode'=> '976'],
            ['name' => 'Montserrat', 'shortname' => 'MS', 'phonecode'=> '1664'],
            ['name' => 'Morocco', 'shortname' => 'MA', 'phonecode'=> '212'],
            ['name' => 'Mozambique', 'shortname' => 'MZ', 'phonecode'=> '258'],
            ['name' => 'Myanmar', 'shortname' => 'MM', 'phonecode'=> '95'],
            ['name' => 'Namibia', 'shortname' => 'NA', 'phonecode'=> '264'],
            ['name' => 'Nauru', 'shortname' => 'NR', 'phonecode'=> '674'],
            ['name' => 'Nepal', 'shortname' => 'NP', 'phonecode'=> '977'],
            ['name' => 'Netherlands Antilles', 'shortname' => 'AN', 'phonecode'=> '599'],
            ['name' => 'Netherlands The', 'shortname' => 'NL', 'phonecode'=> '31'],
            ['name' => 'New Caledonia', 'shortname' => 'NC', 'phonecode'=> '687'],
            ['name' => 'New Zealand', 'shortname' => 'NZ', 'phonecode'=> '64'],
            ['name' => 'Nicaragua', 'shortname' => 'NI', 'phonecode'=> '505'],
            ['name' => 'Niger', 'shortname' => 'NE', 'phonecode'=> '227'],
            ['name' => 'Nigeria', 'shortname' => 'NG', 'phonecode'=> '234'],
            ['name' => 'Niue', 'shortname' => 'NU', 'phonecode'=> '683'],
            ['name' => 'Norfolk Island', 'shortname' => 'NF', 'phonecode'=> '672'],
            ['name' => 'Northern Mariana Islands', 'shortname' => 'MP', 'phonecode'=> '1670'],
            ['name' => 'Norway', 'shortname' => 'NO', 'phonecode'=> '47'],
            ['name' => 'Oman', 'shortname' => 'OM', 'phonecode'=> '968'],
            ['name' => 'Pakistan', 'shortname' => 'PK', 'phonecode'=> '92'],
            ['name' => 'Palau', 'shortname' => 'PW', 'phonecode'=> '680'],
            ['name' => 'Palestinian Territory Occupied', 'shortname' => 'PS', 'phonecode'=> '970'],
            ['name' => 'Panama', 'shortname' => 'PA', 'phonecode'=> '507'],
            ['name' => 'Papua new Guinea', 'shortname' => 'PG', 'phonecode'=> '675'],
            ['name' => 'Paraguay', 'shortname' => 'PY', 'phonecode'=> '595'],
            ['name' => 'Peru', 'shortname' => 'PE', 'phonecode'=> '51'],
            ['name' => 'Philippines', 'shortname' => 'PH', 'phonecode'=> '63'],
            ['name' => 'Pitcairn Island', 'shortname' => 'PN', 'phonecode'=> '0'],
            ['name' => 'Poland', 'shortname' => 'PL', 'phonecode'=> '48'],
            ['name' => 'Portugal', 'shortname' => 'PT', 'phonecode'=> '351'],
            ['name' => 'Puerto Rico', 'shortname' => 'PR', 'phonecode'=> '1787'],
            ['name' => 'Qatar', 'shortname' => 'QA', 'phonecode'=> '974'],
            ['name' => 'Reunion', 'shortname' => 'RE', 'phonecode'=> '262'],
            ['name' => 'Romania', 'shortname' => 'RO', 'phonecode'=> '40'],
            ['name' => 'Russia', 'shortname' => 'RU', 'phonecode'=> '70'],
            ['name' => 'Rwanda', 'shortname' => 'RW', 'phonecode'=> '250'],
            ['name' => 'Saint Helena', 'shortname' => 'SH', 'phonecode'=> '290'],
            ['name' => 'Saint Kitts And Nevis', 'shortname' => 'KN', 'phonecode'=> '1869'],
            ['name' => 'Saint Lucia', 'shortname' => 'LC', 'phonecode'=> '1758'],
            ['name' => 'Saint Pierre and Miquelon', 'shortname' => 'PM', 'phonecode'=> '508'],
            ['name' => 'Saint Vincent And The Grenadines', 'shortname' => 'VC', 'phonecode'=> '1784'],
            ['name' => 'Samoa', 'shortname' => 'WS', 'phonecode'=> '684'],
            ['name' => 'San Marino)', 'shortname' => 'SM', 'phonecode'=> '378'],
            ['name' => 'Sao Tome and Principe', 'shortname' => 'ST', 'phonecode'=> '239'],
            ['name' => 'Saudi Arabia', 'shortname' => 'SA', 'phonecode'=> '966'],
            ['name' => 'Senegal', 'shortname' => 'SN', 'phonecode'=> '221'],
            ['name' => 'Serbia', 'shortname' => 'RS', 'phonecode'=> '381'],
            ['name' => 'Seychelles', 'shortname' => 'SC', 'phonecode'=> '248'],
            ['name' => 'Sierra Leone', 'shortname' => 'SL', 'phonecode'=> '232'],
            ['name' => 'Singapore', 'shortname' => 'SG', 'phonecode'=> '65'],
            ['name' => 'Slovakia', 'shortname' => 'SK', 'phonecode'=> '421'],
            ['name' => 'Slovenia', 'shortname' => 'SI', 'phonecode'=> '386'],
            ['name' => 'Smaller Territories of the UK', 'shortname' => 'XG', 'phonecode'=> '44'],
            ['name' => 'Solomon Islands', 'shortname' => 'SB', 'phonecode'=> '677'],
            ['name' => 'Somalia', 'shortname' => 'SO', 'phonecode'=> '252'],
            ['name' => 'South Africa', 'shortname' => 'ZA', 'phonecode'=> '27'],
            ['name' => 'South Georgia', 'shortname' => 'GS', 'phonecode'=> '0'],
            ['name' => 'South Sudan', 'shortname' => 'SS', 'phonecode'=> '211'],
            ['name' => 'Spain', 'shortname' => 'ES', 'phonecode'=> '34'],
            ['name' => 'Sri Lanka', 'shortname' => 'LK', 'phonecode'=> '94'],
            ['name' => 'Sudan', 'shortname' => 'SD', 'phonecode'=> '249'],
            ['name' => 'Suriname', 'shortname' => 'SR', 'phonecode'=> '597'],
            ['name' => 'Svalbard And Jan Mayen Islands', 'shortname' => 'SJ', 'phonecode'=> '47'],
            ['name' => 'Swaziland', 'shortname' => 'SZ', 'phonecode'=> '268'],
            ['name' => 'Sweden', 'shortname' => 'SE', 'phonecode'=> '46'],
            ['name' => 'Switzerland', 'shortname' => 'CH', 'phonecode'=> '41'],
            ['name' => 'Syria', 'shortname' => 'SY', 'phonecode'=> '963'],
            ['name' => 'Taiwan', 'shortname' => 'TW', 'phonecode'=> '886'],
            ['name' => 'Tajikistan', 'shortname' => 'TJ', 'phonecode'=> '992'],
            ['name' => 'Tanzania', 'shortname' => 'TZ', 'phonecode'=> '255'],
            ['name' => 'Thailand', 'shortname' => 'TH', 'phonecode'=> '66'],
            ['name' => 'Togo', 'shortname' => 'TG', 'phonecode'=> '228'],
            ['name' => 'Tokelau', 'shortname' => 'TK', 'phonecode'=> '690'],
            ['name' => 'Tonga', 'shortname' => 'TO', 'phonecode'=> '676'],
            ['name' => 'Trinidad And Tobago', 'shortname' => 'TT', 'phonecode'=> '1868'],
            ['name' => 'Tunisia', 'shortname' => 'TN', 'phonecode'=> '216'],
            ['name' => 'Turkey', 'shortname' => 'TR', 'phonecode'=> '90'],
            ['name' => 'Turkmenistan', 'shortname' => 'TM', 'phonecode'=> '7370'],
            ['name' => 'Turks And Caicos Islands', 'shortname' => 'TC', 'phonecode'=> '1649'],
            ['name' => 'Tuvalu', 'shortname' => 'TV', 'phonecode'=> '688'],
            ['name' => 'Uganda', 'shortname' => 'UG', 'phonecode'=> '256'],
            ['name' => 'Ukraine', 'shortname' => 'UA', 'phonecode'=> '380'],
            ['name' => 'United Arab Emirates', 'shortname' => 'AE', 'phonecode'=> '971'],
            ['name' => 'United Kingdom', 'shortname' => 'GB', 'phonecode'=> '44'],
            ['name' => 'United States', 'shortname' => 'US', 'phonecode'=> '1'],
            ['name' => 'United States Minor Outlying Islands', 'shortname' => 'UM', 'phonecode'=> '1'],
            ['name' => 'Uruguay', 'shortname' => 'UY', 'phonecode'=> '598'],
            ['name' => 'Uzbekistan', 'shortname' => 'UZ', 'phonecode'=> '998'],
            ['name' => 'Vanuatu', 'shortname' => 'VU', 'phonecode'=> '678'],
            ['name' => 'Vatican City State (Holy See)', 'shortname' => 'VA', 'phonecode'=> '39'],
            ['name' => 'Venezuela', 'shortname' => 'VE', 'phonecode'=> '58'],
            ['name' => 'Vietnam', 'shortname' => 'VN', 'phonecode'=> '84'],
            ['name' => 'Virgin Islands (British)', 'shortname' => 'VG', 'phonecode'=> '1284'],
            ['name' => 'Virgin Islands (US)', 'shortname' => 'VI', 'phonecode'=> '1340'],
            ['name' => 'Wallis And Futuna Islands', 'shortname' => 'WF', 'phonecode'=> '681'],
            ['name' => 'Western Sahara', 'shortname' => 'EH', 'phonecode'=> '212'],
            ['name' => 'Yemen', 'shortname' => 'YE', 'phonecode'=> '967'],
            ['name' => 'Yugoslavia.', 'shortname' => 'YU', 'phonecode'=> '38'],
            ['name' => 'Zambia', 'shortname' => 'ZM', 'phonecode'=> '260'],
            ['name' => 'Zimbabwe', 'shortname' => 'ZW', 'phonecode'=> '263'],
        ];

        foreach ($countries as $key => $value) {
            Country::create($value);
        }
    }
}
